---
- name: install all yum binaries
  hosts: Production-BareMetal-IBM
  vars_files:
    - yum_variables.yaml
  tasks:
    - name: install all yum binaries needed for openshift
      with_items: "{{yum_all_binaries}}"
      ansible.builtin.yum:
        name: "{{item}}"
        state: present
