---
- name: configure virtual network 
  hosts: all
  tasks:
    - name: copy the template virtual_net to root
      ansible.builtin.template:
        src: virtual_net.j2
        dest: /net_ocp.xml
    - name: start the virtual network 
      ansible.builtin.shell:
        chdir: /
        cmd: virsh net-define net_ocp.xml && virsh net-autostart ocp && virsh net-start ocp