---
- name: configure matchbox and openshift installer
  hosts: Production-BareMetal-IBM
  vars_files:
    - misc.yaml
    - cluster_info_variables.yaml
    - secret.yaml
  tasks:
    - name: download matchbox binary 
      ansible.builtin.get_url:
        url: https://github.com/poseidon/matchbox/releases/download/v0.8.3/matchbox-v0.8.3-linux-amd64.tar.gz
        dest: /
    - name: Extract foo.tgz into /var/lib/foo
      ansible.builtin.shell: cd / && tar zxvf matchbox-v0.8.3-linux-amd64.tar.gz
    - name: Copy content of directory 'matchbox'
      ansible.builtin.shell: cp  /matchbox-v0.8.3-linux-amd64/matchbox  /usr/local/bin/matchbox
    - name: Add the user 'matchbox' 
      ansible.builtin.user:
        name: matchbox
      become: yes
    - name: create matchbox directories name
      ansible.builtin.file:
        path: /var/lib/matchbox
        state: directory
        mode: '0755'
      become: yes
    - name: create matchbox directories
      ansible.builtin.file:
        path: /var/lib/matchbox/{{item}}
        recurse: yes
        state: directory
        mode: '0755'
      become: yes
      with_items: ["assets","groups","ignition","profiles"]
    - name: Copy content of directory 'matchbox-local.service'
      ansible.builtin.shell: cp /matchbox-v0.8.3-linux-amd64/contrib/systemd/matchbox-local.service /etc/systemd/system/matchbox.service
    - name: download all openshift binaries  
      ansible.builtin.get_url:
        url: "{{item}}"
        dest: /var/lib/matchbox/assets
      with_items: "{{openshift_binaries}}"
    - name: copy all groups
      ansible.builtin.template:
        src: "{{item}}.j2"
        dest: "/var/lib/matchbox/groups/{{item}}.json"
      with_items: ["bootstrap","master1","master2","master3","worker1","worker2","worker3"]
    - name: copy  bootsrap profile
      ansible.builtin.template:
        src: "bootstrapprofile.j2"
        dest: "/var/lib/matchbox/profiles/bootstrap.json"
    - name: copy  master profile
      ansible.builtin.template:
        src: "masterprofile.j2"
        dest: "/var/lib/matchbox/profiles/master.json"
    - name: copy  worker profile
      ansible.builtin.template:
        src: "workerprofile.j2"
        dest: "/var/lib/matchbox/profiles/worker.json"
    - name: change ownership
      ansible.builtin.shell: chown -R matchbox:matchbox /var/lib/matchbox
    - name: download openshift cli binaries
      ansible.builtin.get_url:
        url: "{{openshift_cli_binaries}}"
        dest: /
    - name: Extract openshift cli binaries
      ansible.builtin.shell: cd / && tar xvf openshift-client-linux.tar.gz
    - name: Copy content of directory 'oc'
      ansible.builtin.shell: cp /openshift-client-linux/oc /usr/local/bin/oc
    - name: Copy content of directory 'kubectl'
      ansible.builtin.shell: cp /openshift-client-linux/kubectl /usr/local/bin/kubectl
    - name: download openshift-installer cli binaries
      ansible.builtin.get_url:
        url: "{{openshift_install_cli_binaries}}"
        dest: /
    - name: Extract openshift cli binaries
      ansible.builtin.shell: cd / && tar xvf openshift-install-linux.tar.gz
    - name: Copy content of directory 'openshift-install'
      ansible.builtin.shell: cp /openshift-install-linux/openshift-install /usr/local/bin/openshift-install
